config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "home/about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div class='text-danger'>
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class:'form-control' %>
  </div>

  <div>
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class:'form-control' %>
  </div>

  <div>
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class:'form-control' %>
  </div>

  <div>
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class:'form-control' %>
  </div>

  <div>
    <%= form.label :twitter, class: "form-label" %>
    <%= form.text_field :twitter, class:'form-control' %>
  </div>

  <div class='mt-3'>
    <%= form.hidden_field :user_id, id: :friend_user_id, value: current_user.id, class:'form-control' %>
  </div>
  <div>
    <%= form.submit class:'btn btn-secondary mt-2' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<section id="<%= dom_id friend %>">
  <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-light text-capitalize"><%= friend.first_name %> <%= friend.last_name %></h1>
      <p class="col-md-8 fw-light fs-5 text-capitalize"><%= friend.email %> | <%= friend.phone %></p>
      <%# <button class="btn btn-primary btn-lg" type="button">Example button</button> %>
      <p>
        <strong>Twitter:</strong>
        <%= friend.twitter %>
      </p>
    </div>
  </div>
</section>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends List</h1>

<div id="friends">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Twitter</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <th scope="row">1</th>
          <td><%=friend.first_name%></td>
          <td><%=friend.last_name%></td>
          <td><%=friend.email%></td>
          <td><%=friend.phone%></td>
          <td><%=friend.twitter%></td>
          <td><%= link_to 'show', friend %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New friend", new_friend_path, class: 'btn btn-secondary' %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:'btn btn-secondary' %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete, class:'btn btn-secondary mt-2' %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to 'About Us', home_about_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%=link_to 'Friends', friends_path, class:'nav-link'%>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%=link_to 'Add Friends', new_friend_path, class:'nav-link'%>
          </li>

          <li class="nav-item">
            <%=link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link'%>
          </li>
          <li class="nav-item">
            <%=link_to 'Edit Profile', edit_user_registration_path, class:'nav-link'%>
          </li>
        <% else %>
          <li class="nav-item">
          <%=link_to 'Sign Up', new_user_registration_path, class:'nav-link'%>
          </li>
          <li class="nav-item">
            <%=link_to 'Sign In',  new_user_session_path, class:'nav-link'%>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Page</h1>

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container mt-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>